from yacs.config import CfgNode as CN

# -----------------------------------------------------------------------------
# Convention about Training / Test specific parameters
# -----------------------------------------------------------------------------
# Whenever an argument can be either used for training or for testing, the
# corresponding name will be post-fixed by a _TRAIN for a training parameter,

# -----------------------------------------------------------------------------
# Config definition
# -----------------------------------------------------------------------------

_C = CN()
# -----------------------------------------------------------------------------
# MODEL
# -----------------------------------------------------------------------------
_C.MODEL = CN()
# Using cuda or cpu for training
_C.MODEL.DEVICE = "cuda"
# ID number of GPU
_C.MODEL.DEVICE_ID = '0'
# Name of backbone
_C.MODEL.NAME = 'resnet50'
# Last stride of backbone
_C.MODEL.LAST_STRIDE = 1
# Path to pretrained model of backbone
_C.MODEL.PRETRAIN_PATH = ''
_C.MODEL.PRETRAIN_HW_RATIO = 1

# Use ImageNet pretrained model to initialize backbone or use self trained model to initialize the whole model
# Options: 'imagenet' , 'self' , 'finetune'
_C.MODEL.PRETRAIN_CHOICE = 'imagenet'

# If train with BNNeck, options: 'bnneck' or 'no'
_C.MODEL.NECK = 'bnneck'
# If train loss include center loss, options: 'yes' or 'no'. Loss with center loss has different optimizer configuration
_C.MODEL.IF_WITH_CENTER = 'no'

_C.MODEL.ID_LOSS_TYPE = 'softmax'
_C.MODEL.ID_LOSS_WEIGHT = 1.0
_C.MODEL.TRIPLET_LOSS_WEIGHT = 1.0

_C.MODEL.METRIC_LOSS_TYPE = 'triplet'
# If train with multi-gpu ddp mode, options: 'True', 'False'
_C.MODEL.DIST_TRAIN = False
# If train with soft triplet loss, options: 'True', 'False'
_C.MODEL.NO_MARGIN = False
# If train with label smooth, options: 'on', 'off'
_C.MODEL.IF_LABELSMOOTH = 'on'
# If train with arcface loss, options: 'True', 'False'
_C.MODEL.COS_LAYER = False
# Cosine-classifier CE (CAL's degenerate form, arXiv:2204.06890): L2-normalize
# the CE classifier weights and features and scale logits by COS_TEMPERATURE
# (= 1/tau; the paper's tau=1/16). The classifier.weight key is unchanged, so
# existing checkpoints warm-start directly. When enabled together with
# distillation, set DISTILL.LOGIT_WEIGHT 0 (teacher logits use a different
# scale); relational KD is unaffected.
_C.MODEL.COS_CLASSIFIER = False
_C.MODEL.COS_TEMPERATURE = 16.0

_C.MODEL.DROPOUT_RATE = 0.0
# Reduce feature dim
_C.MODEL.REDUCE_FEAT_DIM = False
_C.MODEL.FEAT_DIM = 512
# Transformer setting
_C.MODEL.DROP_PATH = 0.1
_C.MODEL.DROP_OUT = 0.0
_C.MODEL.ATT_DROP_RATE = 0.0
_C.MODEL.TRANSFORMER_TYPE = 'None'
_C.MODEL.STRIDE_SIZE = [16, 16]
_C.MODEL.POOLING = 'None'   # gem, avg, max, avg_max
_C.MODEL.STEM_CONV = False

# JPM Parameter
_C.MODEL.JPM = False
_C.MODEL.SHIFT_NUM = 5
_C.MODEL.SHUFFLE_GROUP = 2
_C.MODEL.DEVIDE_LENGTH = 4
_C.MODEL.RE_ARRANGE = True

# SIE Parameter
_C.MODEL.SIE_COE = 3.0
_C.MODEL.SIE_CAMERA = False
_C.MODEL.SIE_VIEW = False

# -----------------------------------------------------------------------------
# INPUT
# -----------------------------------------------------------------------------
_C.INPUT = CN()
# Size of the image during training
_C.INPUT.SIZE_TRAIN = [384, 128]
# Size of the image during test
_C.INPUT.SIZE_TEST = [384, 128]
# Random probability for image horizontal flip
_C.INPUT.PROB = 0.5
# Random probability for random erasing
_C.INPUT.RE_PROB = 0.5
# Values to be used for image normalization
_C.INPUT.PIXEL_MEAN = [0.485, 0.456, 0.406]
# Values to be used for image normalization
_C.INPUT.PIXEL_STD = [0.229, 0.224, 0.225]
# Value of padding size
_C.INPUT.PADDING = 10
# Photometric augmentation (off by default to keep existing recipes intact).
# Probability of applying ColorJitter; hue is kept small on purpose — color is
# a primary discriminative cue in ReID, so large hue shifts (or channel
# permutations a la RandomPhotometricDistort) are harmful
_C.INPUT.CJ_PROB = 0.0
_C.INPUT.CJ_BRIGHTNESS = 0.2
_C.INPUT.CJ_CONTRAST = 0.3
_C.INPUT.CJ_SATURATION = 0.2
_C.INPUT.CJ_HUE = 0.02
# Probability of applying GaussianBlur (kernel 5) with sigma drawn from BLUR_SIGMA
_C.INPUT.BLUR_PROB = 0.0
_C.INPUT.BLUR_SIGMA = [0.1, 2.0]
# NPO occlusion-paste augmentation (FED, arXiv:2112.08740): paste a realistic
# occluder patch onto one image edge. Off by default; patches are generated by
# tools/build_npo_patches.py into NPO_PATCH_DIR (relative to transreid_pytorch/)
_C.INPUT.NPO_PROB = 0.0
_C.INPUT.NPO_PATCH_DIR = 'npo_patches'
# domains (the sample tuple's view/domain slot) that NPO must NOT paste on —
# already-occluded source domains suffer double occlusion otherwise
_C.INPUT.NPO_EXCLUDE_DOMAINS = []
# JPEG-compression augmentation: probability of an in-memory JPEG round-trip
# at a quality drawn uniformly from JPEG_QUALITY (applied after the
# photometric transforms — compression happens after capture)
_C.INPUT.JPEG_PROB = 0.0
_C.INPUT.JPEG_QUALITY = [20, 90]

# -----------------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------------
_C.DATASETS = CN()
# List of the dataset names for training, as present in paths_catalog.py
_C.DATASETS.NAMES = ('market1501')
# Root directory where datasets should be used (and downloaded if not found)
_C.DATASETS.ROOT_DIR = ('../data')
_C.DATASETS.ROOT_TRAIN_DIR = ('../data')
_C.DATASETS.ROOT_VAL_DIR = ('../data')


# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------
_C.DATALOADER = CN()
# Number of data loading threads
_C.DATALOADER.NUM_WORKERS = 16
# Sampler for data loading
_C.DATALOADER.SAMPLER = 'softmax'
# Number of instance for one batch
_C.DATALOADER.NUM_INSTANCE = 16
# remove tail data
_C.DATALOADER.REMOVE_TAIL = 0
# Domain smoothing exponent of the domain_balanced_triplet sampler:
# 1 = proportional to domain size, 0 = uniform across domains
_C.DATALOADER.DOMAIN_ALPHA = 0.5

# -----------------------------------------------------------------------------
# Knowledge distillation (teacher -> student)
# -----------------------------------------------------------------------------
_C.DISTILL = CN()
_C.DISTILL.ENABLED = False
# config file that defines the (frozen) teacher architecture
_C.DISTILL.TEACHER_CONFIG = ''
# trained teacher checkpoint; glob patterns are allowed, e.g.
# logs/reid_vit_base_8gb/transformer_best_*.pth
_C.DISTILL.TEACHER_WEIGHT = ''
# temperature-scaled KL divergence on classifier logits
_C.DISTILL.LOGIT_WEIGHT = 1.0
# similarity-preserving relational loss on batch cosine-similarity matrices;
# dimension-agnostic, works for any student backbone
_C.DISTILL.REL_WEIGHT = 30.0
# direct cosine embedding loss; off by default. With EMBED_PROJ_DIM 0 it
# requires matching embedding dims; set EMBED_PROJ_DIM to the teacher's
# dim (e.g. 768 for ViT-B) to train a loss-only linear projector on the
# student instead (FitNets-style hint; dropped at export)
_C.DISTILL.EMBED_WEIGHT = 0.0
_C.DISTILL.EMBED_PROJ_DIM = 0
_C.DISTILL.TEMPERATURE = 4.0

# ---------------------------------------------------------------------------- #
# Solver
# ---------------------------------------------------------------------------- #
_C.SOLVER = CN()
# Name of optimizer
_C.SOLVER.OPTIMIZER_NAME = "Adam"
# Number of max epoches
_C.SOLVER.MAX_EPOCHS = 100
# Base learning rate
_C.SOLVER.BASE_LR = 3e-4
# Whether using larger learning rate for fc layer
_C.SOLVER.LARGE_FC_LR = False
# Factor of learning bias
_C.SOLVER.BIAS_LR_FACTOR = 1
# Factor of learning bias
_C.SOLVER.SEED = 1234
# Momentum
_C.SOLVER.MOMENTUM = 0.9
# Margin of triplet loss
_C.SOLVER.MARGIN = 0.3
# Learning rate of SGD to learn the centers of center loss
_C.SOLVER.CENTER_LR = 0.5
# Balanced weight of center loss
_C.SOLVER.CENTER_LOSS_WEIGHT = 0.0005

# Settings of weight decay
_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.WEIGHT_DECAY_BIAS = 0.0005

# decay rate of learning rate
_C.SOLVER.GAMMA = 0.1
# decay step of learning rate
_C.SOLVER.STEPS = (40, 70)
# warm up factor
_C.SOLVER.WARMUP_FACTOR = 0.01
#  warm up epochs
_C.SOLVER.WARMUP_EPOCHS = 5
# method of warm up, option: 'constant','linear'
_C.SOLVER.WARMUP_METHOD = "cosine"
# Shift-aware validation: name of a datasets/style_shift.py condition (e.g.
# 'warm'). When set, each eval additionally scores style-shifted queries
# against the clean gallery, and the best model is selected on the mean of
# clean and shifted mAP instead of clean mAP alone. Meant for augmentation
# fine-tunes, where clean mAP alone would keep the warm-start epoch as best.
_C.SOLVER.VAL_SHIFT = ''

# ---------------------------------------------------------------------------- #
# Camera-aware proxy contrastive loss (PPLR/CAP, arXiv:2203.14675)
# ---------------------------------------------------------------------------- #
# Pulls each sample toward the proxies (momentum feature centroids) of the
# same identity seen from OTHER cameras and pushes the hardest other-identity
# proxies, directly shrinking cross-camera intra-class variance. Off by
# default; the proxy bank lives in training state only (not checkpointed —
# it rebuilds within the first epoch after a resume).
_C.CAMPROXY = CN()
_C.CAMPROXY.ENABLED = False
_C.CAMPROXY.WEIGHT = 0.5
_C.CAMPROXY.TAU = 0.07
# retain factor of the old proxy in the momentum update
_C.CAMPROXY.MOMENTUM = 0.2
_C.CAMPROXY.HARD_NEGATIVES = 50

_C.SOLVER.COSINE_MARGIN = 0.5
_C.SOLVER.COSINE_SCALE = 30

# epoch number of saving checkpoints
_C.SOLVER.CHECKPOINT_PERIOD = 10
# iteration of display training log
_C.SOLVER.LOG_PERIOD = 100
# epoch number of validation
_C.SOLVER.EVAL_PERIOD = 1
# save the best model (by validation mAP) as
# <NAME>_best_e<epoch:06d>_map<mAP:.5f>.pth at every evaluation, keeping only
# the latest best; disables the periodic CHECKPOINT_PERIOD snapshots
_C.SOLVER.SAVE_BEST = False
# path to a checkpoint_last.pth written by the trainer; restores model,
# optimizers, scheduler, AMP scaler, epoch, best-model bookkeeping and RNG
# states, then continues training from the next epoch
_C.SOLVER.RESUME = ''
# Number of images per batch
# This is global, so if we have 8 GPUs and IMS_PER_BATCH = 128, each GPU will
# contain 16 images per batch
_C.SOLVER.IMS_PER_BATCH = 64
_C.SOLVER.TRP_L2 = False

# ---------------------------------------------------------------------------- #
# TEST
# ---------------------------------------------------------------------------- #

_C.TEST = CN()
# Number of images per batch during test
_C.TEST.IMS_PER_BATCH = 128
# If test with re-ranking, options: 'True','False'
_C.TEST.RE_RANKING = False
# Path to trained model
_C.TEST.WEIGHT = ""
# Which feature of BNNeck to be used for test, before or after BNNneck, options: 'before' or 'after'
_C.TEST.NECK_FEAT = 'after'
# Whether feature is nomalized before test, if yes, it is equivalent to cosine distance
_C.TEST.FEAT_NORM = 'yes'

# Name for saving the distmat after testing.
_C.TEST.DIST_MAT = "dist_mat.npy"
# Whether calculate the eval score option: 'True', 'False'
_C.TEST.EVAL = False
# ---------------------------------------------------------------------------- #
# Misc options
# ---------------------------------------------------------------------------- #
# Path to checkpoint and saved log of trained model
_C.OUTPUT_DIR = ""
